config/routes.rb
Tix::Application.routes.draw do
  devise_for :users

  resources :events, only: :index
  resources :welcome, only: :index
  
  resources :locations do
    resources :events
  end

  root :to => 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :name
  validates_presence_of :name

  belongs_to :location
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :description, :name
  validates_presence_of :name

  has_many :events
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @page_name = 'Events '

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @location = Location.find(params[:location_id])
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @location = Location.find(params[:location_id])
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @location = Location.find(params[:location_id])
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @location = Location.find(params[:location_id])
    @event = @location.events.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to location_event_path(@location,@event), notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])
    @location = @event.location

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to location_event_path(@event.location, @event), notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    @page_name = 'Locations '

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for [@location, @event] do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    This event is at: <%= @location.name %>
  </p>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', location_event_path(@location, @event) %> |
<%= link_to 'Back', location_events_path %>

app/views/events/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Date</th>
    <th>Location</th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%= link_to event.name, edit_location_event_path(event.location, event) %></td>
    <td><%= event.description %></td>
    <td><i>Coming soon...</i></td>
    <td><%= event.location.name%></td>
  </tr>
<% end %>
</table>

<br />

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>


<%= link_to 'Edit', edit_location_event_path(@location, @event) %> |
<%= link_to 'Back', locations_path %>

app/views/layouts/_footer.html.erb
<!-- Footer -->

  <footer class="row">
    <div class="large-12 columns"><hr>
        <div class="row">

          <div class="large-6 columns">
              <p>&copy; Copyright no one at all. Go to town.</p>
          </div>

          <div class="large-6 small-12 columns">
              <ul class="inline-list right">
                <li><a href="#">Auditions</a></li>
                <li><a href="#">Jobs</a></li>
                <li><a href="#">Members</a></li>
                <li><a href="#">Contact Us</a></li>
              </ul>
          </div>

        </div>
    </div>
  </footer>

<!-- End Footer -->

app/views/layouts/_topnavbar.html.erb
<nav class="top-bar">
<ul class="title-area">
  <!-- Title Area -->
  <li class="name">
    <h1><a href="/">openBoxOffice</a></h1>
  </li>
  <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
  <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
</ul>

<section class="top-bar-section">
<!-- Left Nav Section -->
<ul class="left">
  <li class="divider"></li>
  <li class="active">
    <%= link_to "Locations", locations_path %>
  </li>
  <li>
    <%= link_to "Events", events_path %>
  </li>      	
  <li class="divider"></li>
</ul>
<!-- Right Nav Section -->
<ul class="right">
  <li class="divider hide-for-small"></li>
  <% if user_signed_in? %>
    <li><%= link_to current_user.email, edit_user_registration_path %></li>
    <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Sign Up", new_user_registration_path %></li>
    <li><%= link_to "Log In", new_user_session_path %></li>
  <% end %>
  <li class="divider"></li>
  <li class="has-form">
    <form>
      <div class="row collapse">
        <div class="small-8 columns">
          <input type="text">
        </div>
        <div class="small-4 columns">
          <a href="#" class="alert button">Search</a>
        </div>
      </div>
    </form>
  </li>
  <li class="divider show-for-small"></li>
  <li class="has-form">
    <a class="button" href="#">Join Now!</a>
  </li>
</ul>
</section>
</nav>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "OBO Ticketing" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render :partial => 'layouts/topnavbar' %>

    <% if notice %>
    <div data-alert class="alert-box success radius">
      <%= notice.inspect %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
  <% if alert %>
    <div data-alert class="alert-box alert radius">
      <%= alert.inspect %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>


  <div class="row">
    <div class="large-12 columns">
      <h1><%= @page_name %><small>Portage Area Community Theater</small></h1>
      <hr />
    </div>
  </div>

  <!-- Main Page Content and Sidebar -->
 
  <div class="row">
 
    <!-- Main Content -->
    <div class="large-9 columns" role="content">
    <%= yield %> 
 
    </div>
 
    <!-- End Main Content -->
 
 
    <!-- Sidebar -->
 
    <aside class="large-3 columns">
 
    <div class="panel">
      <h5>Featured</h5>
      <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow.</p>
      <a href="#">Read More &rarr;</a>
    </div>

    <div class="panel">
      <h5>Categories</h5>
      <ul class="side-nav">
        <li><a href="#">Drama</a></li>
        <li><a href="#">Comedy</a></li>
        <li><a href="#">Seasonal</a></li>
        <li><a href="#">Music</a></li>
        <li><a href="#">Talks and Lectures</a></li>
      </ul>
    </div>
 
    </aside>
 
    <!-- End Sidebar -->
  </div>
 
  <!-- End Main Content and Sidebar -->

	    <%= render :partial => 'layouts/footer' %>

	    </div>
	  </div>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "OBO Ticketing" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render :partial => 'layouts/topnavbar' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

	<div class="row">
	    <div class="large-12 columns">
		  <%= yield %>

	    <!-- Content Slider -->

	      <div class="row">
	        <div class="large-12 hide-for-small">

	          <div id="featured">
	              <img src="http://placehold.it/1200x500&text=Slide Image" alt="slide image">
	              <!-- <img src="http://placehold.it/1200x500&text=Slide Image" alt="slide image">
	              <img src="http://placehold.it/1200x500&text=Slide Image" alt="slide image"> -->
	            </div>

	      </div>
	    </div>

	    <!-- End Content Slider -->

	    <!-- Mobile Header -->

	      <div class="row">
	        <div class="large-12 columns show-for-small">

	          <img src="http://placehold.it/1200x700&text=Mobile Header">

	        </div>
	      </div><br>

	    <!-- End Mobile Header -->


	      <div class="row">
	        <div class="large-12 columns">
	          <div class="row">
	            <!-- Shows -->
	            <div class="large-4 small-6 columns">

	              <h4>Upcoming Shows</h4><hr>

	              <div class="row">
	                <div class="large-1 column">
	                  <img src="http://placehold.it/50x50&amp;text=[img]">
	                </div>

	                <div class="large-9 columns">
	                  <h5><%= link_to "Zona Gale", locations_path(1) %></h5>
	                </div>
	              </div><hr>

	              <div class="hide-for-small">
	                <div class="row">
	                  <div class="large-1 column">
	                    <img src="http://placehold.it/50x50&amp;text=[img]">
	                  </div>

	                  <div class="large-9 columns">
		                <h5><%= link_to "Northwoods Dinner Theater", locations_path(2) %></h5>
	                  </div>
	                </div><hr>

	                <div class="row">
	                  <div class="large-1 column">
	                    <img src="http://placehold.it/50x50&amp;text=[img]">
	                  </div>

	                  <div class="large-9 columns">
	                    <h5 class="subheader"><a href="#">Park Shows</a></h5>
	                  </div>
	                </div><hr>

	                <div class="row">
	                  <div class="large-1 column">
	                    <img src="http://placehold.it/50x50&amp;text=[img]">
	                  </div>

	                  <div class="large-9 columns">
	                    <h5 class="subheader"><a href="#">Special Events</a></h5>
	                  </div>
	                </div>
	              </div>
	            </div>
	            <!-- End Shows -->


	            <!-- Image -->

	            <div class="large-4 small-6 columns">
	              <img src="http://placehold.it/300x465&amp;text=Image">
	            </div>

	            <!-- End Image -->


	            <!-- Feed -->

	            <div class="large-4 small-12 columns">

	              <h4>Blog</h4><hr>
	              <div class="panel">
	                <h5><a href="#">Post Title 1</a></h5>

	                <h6 class="subheader">
	                  Risus ligula, aliquam nec fermentum vitae, sollicitudin eget urna. Suspendisse ultrices ornare tempor...
	                </h6>

	                <h6><a href="#">Read More »</a></h6>
	              </div>

	              <div class="panel hide-for-small">
	                <h5><a href="#">Post Title 2 »</a></h5>
	              </div>

	              <div class="panel hide-for-small">
	                <h5><a href="#">Post Title 3 »</a></h5>
	              </div>

	              <a href="#" class="right">Go To Blog »</a>

	            </div>

	            <!-- End Feed -->

	          </div>
	        </div>
	      </div>

	    <!-- End Content -->

	    <%= render :partial => 'layouts/footer' %>

	    </div>
	  </div>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.name %></td>
    <td><%= location.description %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>

<p>
  <b>Description:</b>
  <%= @location.description %>
</p>

<table>
  <tr>
    <th>Event</th>
    <th>Description</th>
  </tr>
  <% @location.events.each do |event| %>
    <tr>
      <td><%= link_to event.name, edit_location_event_path(@location, event) %></td>
      <td><%= event.description %></td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to 'New Event', new_location_event_path(@location) %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/welcome/index.html.erb
<h1>Welcome to PACT</h1>
<p>Ticketing Site for the Portage Area Community Theater</p>